### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by y10987** [lawlawson/prj-rev-bwfs-dasmoto#3]
Grade: Meets Expectations

Good job! You have good syntax, just add alt attributes and more comments. As a challenge, consider adding div tags to your code. You can nest code within the div tags. I think you're ready for it!

**Comment by lawlawson** [comment]
Thank you! I did consider adding a wrapper div I just wasn't sure if it was needed for this particular project. But I guess going forward it would be wise to do. I'll be sure to add alt attributes and more comments in future projects.
